clean2:
	-$(RM) $(CC_DEPS)$(C++_DEPS)$(C_UPPER_DEPS)$(CXX_DEPS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(CPP_DEPS)
	-$(RM) $(OBJS) *.elf
	-@echo ' '
    
*.elf: $(wildcard C:/Tools/RT-ThreadStudio/workspace/charging_pile/linkscripts/STM32F103RC/link.lds)
