Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

if GetDepend(['USE_UPPER_END']):
    src += Glob('*.cxx')
    src += Glob('things/decos/*.cxx')
    src += Glob('things/decos/params/*.cxx')

if GetDepend(['USE_LOWER_END']):
    src += [
        'app.cxx',
        'lower_major_app.cxx',
        'thing.cxx',
        'local_thing.cxx',
        'loader.cxx',
        'lower_loader.cxx',
        'lower_ota_app.cxx'
    ]
    src += Glob('things/decos/*.cxx')
    src += Glob('things/decos/params/*.cxx')

CPPPATH = [
    cwd,
    cwd + '/things/decos',
    cwd + '/things/decos/params',
]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
