Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.cxx')
CPPPATH = [
    cwd,
]

group = DefineGroup('Components', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
