Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.cxx')

if GetDepend(['USE_LOWER_END']):
    src += Glob('lower_end/*.cxx')

if GetDepend(['USE_UPPER_END']):
    src += Glob('upper_end/*.cxx')
CPPPATH = [
    cwd,
    cwd + '/lower_end',
    cwd + '/upper_end',
]

group = DefineGroup('Config', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
