Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []

if GetDepend(['USE_UPPER_END']):
    src += Glob('*.cxx')

CPPPATH = [
    cwd,
]

group = DefineGroup('Ui', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
